INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (1, 'Situé près d''une station de ski, lac vosgien', null, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (3, 'Pont à haubans, Aveyron, France', null, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (13, 'Must a visité dans la ville des lumières. Des vendeurs à la sauvette en vendent de petits exemplaires...', null, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (15, '''Ville de la moutarde'' dixit Patrick CHIRAC', null, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (17, 'Place inscrit au patrimoine mondial de l''UNESCO en Lorraine', null, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (19, 'Musée d''un alcool de fermatation d''houblons, situé dans le departement de la meuse.', null, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (21, 'La ville du Pastaga, de la pétanque et des films Taxi', null, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (23, 'On ne peut y accèder qu''en marée basse, on peut croire qu''il est breton, mais en réalité il est normand', null, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (25, 'Sépare la France et l''Espagne, l''Andorre', null, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (27, 'Entrée en France du tunnel sous la manche', null, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (30, '14 Juillet', 29, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (31, 'Monopoly', 29, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (32, 'Avenue', 29, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (33, '8ème arrondissement de Paris', 29, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (34, 'De Concorde à Charles Gaulle', 29, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (36, 'Bord de mer', 35, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (37, 'Plage des Abatilles', 35, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (38, 'Observatoire Ste Cécile', 35, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (39, 'Passerelle St Paul', 35, null);
INSERT INTO public.indices (id, description, destinationfinal_id, lieux_id) VALUES (40, 'Parc Mauresque', 35, null);