INSERT INTO public.indices (id, description, destinationfinal_id) VALUES (1, 'ceci est l''indice du lieu 1 de la partie 1', null);
INSERT INTO public.indices (id, description, destinationfinal_id) VALUES (3, 'ceci est l''indice du lieu 2 de la partie 1', null);
INSERT INTO public.indices (id, description, destinationfinal_id) VALUES (5, 'ceci est l''indice du lieu 3 de la partie 1', null);
INSERT INTO public.indices (id, description, destinationfinal_id) VALUES (7, 'ceci est l''indice du lieu 4 de la partie 1', null);
INSERT INTO public.indices (id, description, destinationfinal_id) VALUES (9, 'ceci est l''indice du lieu 5 de la partie 1', null);
INSERT INTO public.indices (id, description, destinationfinal_id) VALUES (12, 'ceci est l''indice 1 de la DF partie 1', 11);
INSERT INTO public.indices (id, description, destinationfinal_id) VALUES (13, 'ceci est l''indice 2 de la DF partie 1', 11);
INSERT INTO public.indices (id, description, destinationfinal_id) VALUES (14, 'ceci est l''indice 3 de la DF partie 1', 11);
INSERT INTO public.indices (id, description, destinationfinal_id) VALUES (15, 'ceci est l''indice 4 de la DF partie 1', 11);
INSERT INTO public.indices (id, description, destinationfinal_id) VALUES (16, 'ceci est l''indice 5 de la DF partie 1', 11);
INSERT INTO public.indices (id, description, destinationfinal_id) VALUES (18, 'ceci est l''indice 1 de la DF partie 2', 17);
INSERT INTO public.indices (id, description, destinationfinal_id) VALUES (19, 'ceci est l''indice 2 de la DF partie 2', 17);
INSERT INTO public.indices (id, description, destinationfinal_id) VALUES (20, 'ceci est l''indice 3 de la DF partie 2', 17);
INSERT INTO public.indices (id, description, destinationfinal_id) VALUES (21, 'ceci est l''indice 4 de la DF partie 2', 17);
INSERT INTO public.indices (id, description, destinationfinal_id) VALUES (22, 'ceci est l''indice 5 de la DF partie 2', 17);